package GreenApps.model;
// Generated Jun 19, 2020 8:52:51 PM by Hibernate Tools 4.3.1



/**
 * DetalleDevolucionCliente generated by hbm2java
 */
public class DetalleDevolucionCliente  implements java.io.Serializable {


     private Integer idDetalleDevolucionCliente;
     private int idDevolucionCliente;
     private int idProducto;
     private String codigoProducto;
     private String nombreProducto;
     private float valorVentaProducto;
     private int unidadesDevueltas;
     private float totalDetalleDevolucionCliente;

    public DetalleDevolucionCliente() {
    }

    public DetalleDevolucionCliente(int idDevolucionCliente, int idProducto, String codigoProducto, String nombreProducto, float valorVentaProducto, int unidadesDevueltas, float totalDetalleDevolucionCliente) {
       this.idDevolucionCliente = idDevolucionCliente;
       this.idProducto = idProducto;
       this.codigoProducto = codigoProducto;
       this.nombreProducto = nombreProducto;
       this.valorVentaProducto = valorVentaProducto;
       this.unidadesDevueltas = unidadesDevueltas;
       this.totalDetalleDevolucionCliente = totalDetalleDevolucionCliente;
    }
   
    public Integer getIdDetalleDevolucionCliente() {
        return this.idDetalleDevolucionCliente;
    }
    
    public void setIdDetalleDevolucionCliente(Integer idDetalleDevolucionCliente) {
        this.idDetalleDevolucionCliente = idDetalleDevolucionCliente;
    }
    public int getIdDevolucionCliente() {
        return this.idDevolucionCliente;
    }
    
    public void setIdDevolucionCliente(int idDevolucionCliente) {
        this.idDevolucionCliente = idDevolucionCliente;
    }
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }
    public String getCodigoProducto() {
        return this.codigoProducto;
    }
    
    public void setCodigoProducto(String codigoProducto) {
        this.codigoProducto = codigoProducto;
    }
    public String getNombreProducto() {
        return this.nombreProducto;
    }
    
    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }
    public float getValorVentaProducto() {
        return this.valorVentaProducto;
    }
    
    public void setValorVentaProducto(float valorVentaProducto) {
        this.valorVentaProducto = valorVentaProducto;
    }
    public int getUnidadesDevueltas() {
        return this.unidadesDevueltas;
    }
    
    public void setUnidadesDevueltas(int unidadesDevueltas) {
        this.unidadesDevueltas = unidadesDevueltas;
    }
    public float getTotalDetalleDevolucionCliente() {
        return this.totalDetalleDevolucionCliente;
    }
    
    public void setTotalDetalleDevolucionCliente(float totalDetalleDevolucionCliente) {
        this.totalDetalleDevolucionCliente = totalDetalleDevolucionCliente;
    }




}


