package GreenApps.model;
// Generated Jun 19, 2020 8:52:51 PM by Hibernate Tools 4.3.1



/**
 * DetalleDevolucionProveedor generated by hbm2java
 */
public class DetalleDevolucionProveedor  implements java.io.Serializable {


     private Integer idDetalleDevolucionProveedor;
     private int idDevolucionProveedor;
     private int idProducto;
     private String codigoProducto;
     private String nombreProducto;
     private float valorVentaProducto;
     private int unidadesDevueltas;
     private float totalDetalleDevolucionProveedor;

    public DetalleDevolucionProveedor() {
    }

    public DetalleDevolucionProveedor(int idDevolucionProveedor, int idProducto, String codigoProducto, String nombreProducto, float valorVentaProducto, int unidadesDevueltas, float totalDetalleDevolucionProveedor) {
       this.idDevolucionProveedor = idDevolucionProveedor;
       this.idProducto = idProducto;
       this.codigoProducto = codigoProducto;
       this.nombreProducto = nombreProducto;
       this.valorVentaProducto = valorVentaProducto;
       this.unidadesDevueltas = unidadesDevueltas;
       this.totalDetalleDevolucionProveedor = totalDetalleDevolucionProveedor;
    }
   
    public Integer getIdDetalleDevolucionProveedor() {
        return this.idDetalleDevolucionProveedor;
    }
    
    public void setIdDetalleDevolucionProveedor(Integer idDetalleDevolucionProveedor) {
        this.idDetalleDevolucionProveedor = idDetalleDevolucionProveedor;
    }
    public int getIdDevolucionProveedor() {
        return this.idDevolucionProveedor;
    }
    
    public void setIdDevolucionProveedor(int idDevolucionProveedor) {
        this.idDevolucionProveedor = idDevolucionProveedor;
    }
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }
    public String getCodigoProducto() {
        return this.codigoProducto;
    }
    
    public void setCodigoProducto(String codigoProducto) {
        this.codigoProducto = codigoProducto;
    }
    public String getNombreProducto() {
        return this.nombreProducto;
    }
    
    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }
    public float getValorVentaProducto() {
        return this.valorVentaProducto;
    }
    
    public void setValorVentaProducto(float valorVentaProducto) {
        this.valorVentaProducto = valorVentaProducto;
    }
    public int getUnidadesDevueltas() {
        return this.unidadesDevueltas;
    }
    
    public void setUnidadesDevueltas(int unidadesDevueltas) {
        this.unidadesDevueltas = unidadesDevueltas;
    }
    public float getTotalDetalleDevolucionProveedor() {
        return this.totalDetalleDevolucionProveedor;
    }
    
    public void setTotalDetalleDevolucionProveedor(float totalDetalleDevolucionProveedor) {
        this.totalDetalleDevolucionProveedor = totalDetalleDevolucionProveedor;
    }




}


