package GreenApps.model;
// Generated Jan 18, 2020 10:18:03 PM by Hibernate Tools 4.3.1



/**
 * DetalleServicio generated by hbm2java
 */
public class DetalleServicio  implements java.io.Serializable {


     private Integer idDetalleServicio;
     private int idServicio;
     private int idProducto;
     private String codigoProducto;
     private String nombreProducto;
     private float valorVentaProducto;
     private String iva;
     private int unidadesVendidas;
     private float totalDetalleServicio;

    public DetalleServicio() {
    }

    public DetalleServicio(int idServicio, int idProducto, String codigoProducto, String nombreProducto, float valorVentaProducto, String iva, int unidadesVendidas, float totalDetalleServicio) {
       this.idServicio = idServicio;
       this.idProducto = idProducto;
       this.codigoProducto = codigoProducto;
       this.nombreProducto = nombreProducto;
       this.valorVentaProducto = valorVentaProducto;
       this.iva = iva;
       this.unidadesVendidas = unidadesVendidas;
       this.totalDetalleServicio = totalDetalleServicio;
    }
   
    public Integer getIdDetalleServicio() {
        return this.idDetalleServicio;
    }
    
    public void setIdDetalleServicio(Integer idDetalleServicio) {
        this.idDetalleServicio = idDetalleServicio;
    }
    public int getIdServicio() {
        return this.idServicio;
    }
    
    public void setIdServicio(int idServicio) {
        this.idServicio = idServicio;
    }
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }
    public String getCodigoProducto() {
        return this.codigoProducto;
    }
    
    public void setCodigoProducto(String codigoProducto) {
        this.codigoProducto = codigoProducto;
    }
    public String getNombreProducto() {
        return this.nombreProducto;
    }
    
    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }
    public float getValorVentaProducto() {
        return this.valorVentaProducto;
    }
    
    public void setValorVentaProducto(float valorVentaProducto) {
        this.valorVentaProducto = valorVentaProducto;
    }
    public String getIva() {
        return this.iva;
    }
    
    public void setIva(String iva) {
        this.iva = iva;
    }
    public int getUnidadesVendidas() {
        return this.unidadesVendidas;
    }
    
    public void setUnidadesVendidas(int unidadesVendidas) {
        this.unidadesVendidas = unidadesVendidas;
    }
    public float getTotalDetalleServicio() {
        return this.totalDetalleServicio;
    }
    
    public void setTotalDetalleServicio(float totalDetalleServicio) {
        this.totalDetalleServicio = totalDetalleServicio;
    }




}


