package GreenApps.model;
// Generated Jun 19, 2020 8:52:51 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DevolucionCliente generated by hbm2java
 */
public class DevolucionCliente  implements java.io.Serializable {


     private Integer idDevolucionCliente;
     private String numeroDevolucionCliente;
     private int idEmpleado;
     private int idPersona;
     private float totalDevolucionCliente;
     private int idTipoTransaccion;
     private Date fechaDevolucionCliente;

    public DevolucionCliente() {
    }

    public DevolucionCliente(String numeroDevolucionCliente, int idEmpleado, int idPersona, float totalDevolucionCliente, int idTipoTransaccion, Date fechaDevolucionCliente) {
       this.numeroDevolucionCliente = numeroDevolucionCliente;
       this.idEmpleado = idEmpleado;
       this.idPersona = idPersona;
       this.totalDevolucionCliente = totalDevolucionCliente;
       this.idTipoTransaccion = idTipoTransaccion;
       this.fechaDevolucionCliente = fechaDevolucionCliente;
    }
   
    public Integer getIdDevolucionCliente() {
        return this.idDevolucionCliente;
    }
    
    public void setIdDevolucionCliente(Integer idDevolucionCliente) {
        this.idDevolucionCliente = idDevolucionCliente;
    }
    public String getNumeroDevolucionCliente() {
        return this.numeroDevolucionCliente;
    }
    
    public void setNumeroDevolucionCliente(String numeroDevolucionCliente) {
        this.numeroDevolucionCliente = numeroDevolucionCliente;
    }
    public int getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public int getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }
    public float getTotalDevolucionCliente() {
        return this.totalDevolucionCliente;
    }
    
    public void setTotalDevolucionCliente(float totalDevolucionCliente) {
        this.totalDevolucionCliente = totalDevolucionCliente;
    }
    public int getIdTipoTransaccion() {
        return this.idTipoTransaccion;
    }
    
    public void setIdTipoTransaccion(int idTipoTransaccion) {
        this.idTipoTransaccion = idTipoTransaccion;
    }
    public Date getFechaDevolucionCliente() {
        return this.fechaDevolucionCliente;
    }
    
    public void setFechaDevolucionCliente(Date fechaDevolucionCliente) {
        this.fechaDevolucionCliente = fechaDevolucionCliente;
    }




}


