package GreenApps.model;
// Generated Jan 18, 2020 10:18:03 PM by Hibernate Tools 4.3.1



/**
 * EmpleadoUsuarios generated by hbm2java
 */
public class EmpleadoUsuarios  implements java.io.Serializable {


     private Integer idEmpleadoUsuarios;
     private int idEmpleado;
     private int idPerfiles;

    public EmpleadoUsuarios() {
    }

    public EmpleadoUsuarios(int idEmpleado, int idPerfiles) {
       this.idEmpleado = idEmpleado;
       this.idPerfiles = idPerfiles;
    }
   
    public Integer getIdEmpleadoUsuarios() {
        return this.idEmpleadoUsuarios;
    }
    
    public void setIdEmpleadoUsuarios(Integer idEmpleadoUsuarios) {
        this.idEmpleadoUsuarios = idEmpleadoUsuarios;
    }
    public int getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public int getIdPerfiles() {
        return this.idPerfiles;
    }
    
    public void setIdPerfiles(int idPerfiles) {
        this.idPerfiles = idPerfiles;
    }




}


