package GreenApps.model;
// Generated Mar 15, 2020 9:43:40 PM by Hibernate Tools 4.3.1



/**
 * PresentacionProducto generated by hbm2java
 */
public class PresentacionProducto  implements java.io.Serializable {


     private Integer idPresentacionProducto;
     private String descripcionPresentacionPro;

    public PresentacionProducto() {
    }

    public PresentacionProducto(String descripcionPresentacionPro) {
       this.descripcionPresentacionPro = descripcionPresentacionPro;
    }
   
    public Integer getIdPresentacionProducto() {
        return this.idPresentacionProducto;
    }
    
    public void setIdPresentacionProducto(Integer idPresentacionProducto) {
        this.idPresentacionProducto = idPresentacionProducto;
    }
    public String getDescripcionPresentacionPro() {
        return this.descripcionPresentacionPro;
    }
    
    public void setDescripcionPresentacionPro(String descripcionPresentacionPro) {
        this.descripcionPresentacionPro = descripcionPresentacionPro;
    }




}


