package GreenApps.model;
// Generated Jan 18, 2020 10:18:03 PM by Hibernate Tools 4.3.1



/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer idProducto;
     private String codigoProducto;
     private String nombreProducto;
     private String descripcionProducto;
     private int stockProducto;
     private float valorCompraProducto;
     private float valorVentaProducto;
     private int stockMinimo;
     private String iva;
     private int idCategoria;
     private int idPresentacionProducto;
     private int idUbicacionProducto;

    public Producto() {
    }

    public Producto(String codigoProducto, String nombreProducto, String descripcionProducto, int stockProducto, float valorCompraProducto, float valorVentaProducto, int stockMinimo, String iva, int idCategoria, int idPresentacionProducto, int idUbicacionProducto) {
       this.codigoProducto = codigoProducto;
       this.nombreProducto = nombreProducto;
       this.descripcionProducto = descripcionProducto;
       this.stockProducto = stockProducto;
       this.valorCompraProducto = valorCompraProducto;
       this.valorVentaProducto = valorVentaProducto;
       this.stockMinimo = stockMinimo;
       this.iva = iva;
       this.idCategoria = idCategoria;
       this.idPresentacionProducto = idPresentacionProducto;
       this.idUbicacionProducto = idUbicacionProducto;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public String getCodigoProducto() {
        return this.codigoProducto;
    }
    
    public void setCodigoProducto(String codigoProducto) {
        this.codigoProducto = codigoProducto;
    }
    public String getNombreProducto() {
        return this.nombreProducto;
    }
    
    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }
    public String getDescripcionProducto() {
        return this.descripcionProducto;
    }
    
    public void setDescripcionProducto(String descripcionProducto) {
        this.descripcionProducto = descripcionProducto;
    }
    public int getStockProducto() {
        return this.stockProducto;
    }
    
    public void setStockProducto(int stockProducto) {
        this.stockProducto = stockProducto;
    }
    public float getValorCompraProducto() {
        return this.valorCompraProducto;
    }
    
    public void setValorCompraProducto(float valorCompraProducto) {
        this.valorCompraProducto = valorCompraProducto;
    }
    public float getValorVentaProducto() {
        return this.valorVentaProducto;
    }
    
    public void setValorVentaProducto(float valorVentaProducto) {
        this.valorVentaProducto = valorVentaProducto;
    }
    public int getStockMinimo() {
        return this.stockMinimo;
    }
    
    public void setStockMinimo(int stockMinimo) {
        this.stockMinimo = stockMinimo;
    }
    public String getIva() {
        return this.iva;
    }
    
    public void setIva(String iva) {
        this.iva = iva;
    }
    public int getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(int idCategoria) {
        this.idCategoria = idCategoria;
    }
    public int getIdPresentacionProducto() {
        return this.idPresentacionProducto;
    }
    
    public void setIdPresentacionProducto(int idPresentacionProducto) {
        this.idPresentacionProducto = idPresentacionProducto;
    }
    public int getIdUbicacionProducto() {
        return this.idUbicacionProducto;
    }
    
    public void setIdUbicacionProducto(int idUbicacionProducto) {
        this.idUbicacionProducto = idUbicacionProducto;
    }




}


