package GreenApps.model;
// Generated Jan 18, 2020 10:18:03 PM by Hibernate Tools 4.3.1



/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private Integer idRoles;
     private String codigoRol;
     private String nombreRol;
     private int idModulos;

    public Roles() {
    }

    public Roles(String codigoRol, String nombreRol, int idModulos) {
       this.codigoRol = codigoRol;
       this.nombreRol = nombreRol;
       this.idModulos = idModulos;
    }
   
    public Integer getIdRoles() {
        return this.idRoles;
    }
    
    public void setIdRoles(Integer idRoles) {
        this.idRoles = idRoles;
    }
    public String getCodigoRol() {
        return this.codigoRol;
    }
    
    public void setCodigoRol(String codigoRol) {
        this.codigoRol = codigoRol;
    }
    public String getNombreRol() {
        return this.nombreRol;
    }
    
    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }
    public int getIdModulos() {
        return this.idModulos;
    }
    
    public void setIdModulos(int idModulos) {
        this.idModulos = idModulos;
    }




}


