package GreenApps.model;
// Generated Jan 18, 2020 10:18:03 PM by Hibernate Tools 4.3.1

import GreenApps.util.HibernateUtil;
import java.beans.Transient;
import java.util.Date;
import org.hibernate.Session;

/**
 * Servicio generated by hbm2java
 */
public class Servicio implements java.io.Serializable {

    private Integer idServicio;
    private String numeroServicio;
    private String placa;
    private int idMoto;
    private int idMecanico;
    private String observacionServicio;
    private int idEmpleado;
    private int idPersona;
    private float totalServicio;
    private String totalDescuentoServicio;
    private int idTipoTransaccion;
    private Date fechaServicio;
    private Byte estadoServicio;

    @Transient
    public int getIdentificacionPersona() {

        try {
            Session sessionIdentificacionPersona = HibernateUtil.getSessionFactory().openSession();
            Persona p = (Persona) sessionIdentificacionPersona.get(Persona.class, this.idPersona);
            return p.getIdentificacionPersona();
        } catch (Exception e) {

            return 0;
        }

    }

    @Transient
    public void setIdentificacionPersona(int identificacionPersona) {

    }

    public Servicio() {
    }

    public Servicio(String numeroServicio, String placa, int idMoto, int idMecanico, String observacionServicio, int idEmpleado, int idPersona, float totalServicio, int idTipoTransaccion, Date fechaServicio) {
        this.numeroServicio = numeroServicio;
        this.placa = placa;
        this.idMoto = idMoto;
        this.idMecanico = idMecanico;
        this.observacionServicio = observacionServicio;
        this.idEmpleado = idEmpleado;
        this.idPersona = idPersona;
        this.totalServicio = totalServicio;
        this.idTipoTransaccion = idTipoTransaccion;
        this.fechaServicio = fechaServicio;
    }

    public Servicio(String numeroServicio, String placa, int idMoto, int idMecanico, String observacionServicio, int idEmpleado, int idPersona, float totalServicio, String totalDescuentoServicio, int idTipoTransaccion, Date fechaServicio, Byte estadoServicio) {
        this.numeroServicio = numeroServicio;
        this.placa = placa;
        this.idMoto = idMoto;
        this.idMecanico = idMecanico;
        this.observacionServicio = observacionServicio;
        this.idEmpleado = idEmpleado;
        this.idPersona = idPersona;
        this.totalServicio = totalServicio;
        this.totalDescuentoServicio = totalDescuentoServicio;
        this.idTipoTransaccion = idTipoTransaccion;
        this.fechaServicio = fechaServicio;
        this.estadoServicio = estadoServicio;
    }

    public Integer getIdServicio() {
        return this.idServicio;
    }

    public void setIdServicio(Integer idServicio) {
        this.idServicio = idServicio;
    }

    public String getNumeroServicio() {
        return this.numeroServicio;
    }

    public void setNumeroServicio(String numeroServicio) {
        this.numeroServicio = numeroServicio;
    }

    public String getPlaca() {
        return this.placa;
    }

    public void setPlaca(String placa) {
        this.placa = placa;
    }

    public int getIdMoto() {
        return this.idMoto;
    }

    public void setIdMoto(int idMoto) {
        this.idMoto = idMoto;
    }

    public int getIdMecanico() {
        return this.idMecanico;
    }

    public void setIdMecanico(int idMecanico) {
        this.idMecanico = idMecanico;
    }

    public String getObservacionServicio() {
        return this.observacionServicio;
    }

    public void setObservacionServicio(String observacionServicio) {
        this.observacionServicio = observacionServicio;
    }

    public int getIdEmpleado() {
        return this.idEmpleado;
    }

    public void setIdEmpleado(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }

    public int getIdPersona() {
        return this.idPersona;
    }

    public void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }

    public float getTotalServicio() {
        return this.totalServicio;
    }

    public void setTotalServicio(float totalServicio) {
        this.totalServicio = totalServicio;
    }

    public String getTotalDescuentoServicio() {
        return this.totalDescuentoServicio;
    }

    public void setTotalDescuentoServicio(String totalDescuentoServicio) {
        this.totalDescuentoServicio = totalDescuentoServicio;
    }

    public int getIdTipoTransaccion() {
        return this.idTipoTransaccion;
    }

    public void setIdTipoTransaccion(int idTipoTransaccion) {
        this.idTipoTransaccion = idTipoTransaccion;
    }

    public Date getFechaServicio() {
        return this.fechaServicio;
    }

    public void setFechaServicio(Date fechaServicio) {
        this.fechaServicio = fechaServicio;
    }

    public Byte getEstadoServicio() {
        return this.estadoServicio;
    }

    public void setEstadoServicio(Byte estadoServicio) {
        this.estadoServicio = estadoServicio;
    }

}
