package GreenApps.model;
// Generated Mar 15, 2020 9:43:40 PM by Hibernate Tools 4.3.1



/**
 * TipoTransaccion generated by hbm2java
 */
public class TipoTransaccion  implements java.io.Serializable {


     private Integer idTipoTransaccion;
     private String descripcionTransaccion;

    public TipoTransaccion() {
    }

    public TipoTransaccion(String descripcionTransaccion) {
       this.descripcionTransaccion = descripcionTransaccion;
    }
   
    public Integer getIdTipoTransaccion() {
        return this.idTipoTransaccion;
    }
    
    public void setIdTipoTransaccion(Integer idTipoTransaccion) {
        this.idTipoTransaccion = idTipoTransaccion;
    }
    public String getDescripcionTransaccion() {
        return this.descripcionTransaccion;
    }
    
    public void setDescripcionTransaccion(String descripcionTransaccion) {
        this.descripcionTransaccion = descripcionTransaccion;
    }




}


