package GreenApps.model;
// Generated Jan 18, 2020 10:18:03 PM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String userEmp;
     private String passEmp;
     private int idEmpleado;

    public Usuario() {
    }

    public Usuario(String userEmp, String passEmp, int idEmpleado) {
       this.userEmp = userEmp;
       this.passEmp = passEmp;
       this.idEmpleado = idEmpleado;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getUserEmp() {
        return this.userEmp;
    }
    
    public void setUserEmp(String userEmp) {
        this.userEmp = userEmp;
    }
    public String getPassEmp() {
        return this.passEmp;
    }
    
    public void setPassEmp(String passEmp) {
        this.passEmp = passEmp;
    }
    public int getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }




}


